[package]
name = "aoc-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = "0.0.302"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.10.4"
rustc-hash = "1.1.0"
